version: '2.1'
services:
  config:
    build: configservice
    ports:
      - 8888:8888

  registry:
    build: registry

  gateway:
    build: gateway

  shareservice:
    build: shareservice
    ports:
      - 6001:6001
