version: '3'
services:
  configservice:
    build: configservice
    restart: always
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "20"

  registry:
    build: registry
    restart: always
    depends_on:
      - configservice
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "20"

#  gateway:
#    build: gateway
#    restart: always
#    depends_on:
#      - configservice
#    ports:
#      - 9191:9191
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "20"
#
#  shareservice:
#    build: shareservice
#    restart: always
#    depends_on:
#      - configservice
#    ports:
#      - 6001:6001
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "20"
#
#  historyservice:
#    build: historyservice
#    restart: always
#    depends_on:
#      - configservice
#    ports:
#      - 6002:6002
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "20"
#
#  redis:
#    image: "redis:alpine"
