spring:
  application:
    name: gateway
  jackson.serialization.indent_output: true
#  config:
#    import: "optional:configserver:http://configservice:8888"
#    fail-fast: true
  cloud:
    gateway:
      routes:
        - id: shareservice
#          uri: lb://localhost:6001
          uri: lb://shareservice
          predicates:
            - Path=/shares/**
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/fallback


management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always
management.endpoints.web.base-path: '/'

management.health.diskspace.enabled: false
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10000
      failureRateThreshold: 60
      eventConsumerBufferSize: 10
      registerHealthIndicator: true

resilience4j.ratelimiter:
  configs:
    default:
      registerHealthIndicator: true

server:
  port: 9191