spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:"
  cloud:
    gateway:
      routes:
        - id: shareservice
          uri: lb://shareservice
          predicates:
            - Path=/shares/**
          filters:
            - name: CircuitBreaker
              args: shareservice
              fallbackuri: forward:/userServiceFallBack

