spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://configservice:8888"
  cloud:
    gateway:
      routes:
        - id: shareservice
          uri: lb://shareservice
          predicates:
            - Path=/shares/**

