spring:
  application:
    name: registry
#  config:
#    import: "optional:configserver:http://configservice:8888"
#    fail-fast: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

server:
  port: 8761
